Update README.md
nightscout/cgm-remote-monitor pull request #6178
Opened 2020-10-01 12:18 UTC by Raulkumar

2020-10-05 07:27 UTC, inventor96 requested changes
Thanks for going through and correcting all this! Just a couple minor corrections, and then I think this would be a very nice update to include.

2020-10-05 07:27 UTC, inventor96 commented on README.md
> +<!-- END doctoc generated TOC please keep comment here to allow auto-update -->
Since this is used by doctoc and not seen by users, this should probably be left without the hyphen.

2020-10-05 07:27 UTC, inventor96 commented on README.md
> +hostings for you and even many of the developers run their production sites in Heroku due to convenience.
If I'm not mistaken, "hosting" is actually the correct form here.

2020-10-05 07:27 UTC, inventor96 commented on README.md
> +  * `ALARM_WARN_MINS` (`30 60 90 120`) - Number of minutes to snooze warning alarms (that aren't tagged as high or low), space-separated for options in the browser, first used for the pushover
Since Pushover is a noun (it's a service that is used by Nightscout), "the pushover" should be just "Pushover".

2020-10-05 07:27 UTC, inventor96 commented on README.md
> +  * `Color` - Shows current BG and trend arrow. White text on color background.
The "a" should be left here.

2020-10-05 07:27 UTC, inventor96 commented on README.md
> +  This plugin intended for the purpose of automatically snoozing alarms when the CGM indicates high blood sugar but there is also insulin on board (IOB) and secondly, alerting to user that it might b
It looks like "in" was intended to be "is".

2020-10-05 07:27 UTC, inventor96 commented on README.md
> -  * `DBSIZE_WARN_PERCENTAGE` (`60`) - Threshold to show first warning about database size. When database reach this percentage of `DBSIZE_MAX` size - pill will show size in yellow.
I think it makes more sense to change this to "The pill" instead of removing "pill" altogether.

2020-10-05 07:27 UTC, inventor96 commented on README.md
> +  This plugin should be enabled by default if needed can be disabled by adding `dbsize` to the list of disabled plugins, for example: `DISABLE="dbsize"`.
Probably more correct to change this to "... by default. If needed, it can be disabled ..."

2020-10-05 07:31 UTC, inventor96 commented
Also, could you change the PR to target the `nightscout:dev` branch instead of `nightscout:master`? Even though it's all just documentation changes and not code changes, it's best practice to merge changes into `dev` first.

2021-01-17 18:26 UTC, sulkaharo commented
Closing due to author not making changes based on comments.

2021-01-17 18:26 UTC, closed without merging